apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: streamlit-database
  namespace: user-fersoil
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: zfs-rs128k
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-deployment
  labels:
    app: streamlit
    www: "true"
  namespace: user-fersoil
spec:
  replicas: 1
  selector:
    matchLabels:
      www: "true"
      app: streamlit
  template:
    metadata:
      labels:
        www: "true"
        app: streamlit
    spec:
      containers:
        - name: streamlit
          image: tkwiecinski/streamlit_translator:v0.1.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
          livenessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
              scheme: HTTP
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
              scheme: HTTP
            timeoutSeconds: 1
          volumeMounts:
          - mountPath: "/volume"
            name: database
          resources:
            limits:
              cpu: 1
              memory: 5Gi
            requests:
              cpu: 1
              memory: 1Gi
      automountServiceAccountToken: false
      volumes:
        - name: database
          persistentVolumeClaim:
            claimName: streamlit-database
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-fersoil
  namespace: user-fersoil
spec:
  type: ClusterIP
  selector:
    app: streamlit
  ports:
    - name: streamlit-port
      protocol: TCP
      port: 8501
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: streamlit-app
  namespace: user-fersoil
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: user-fersoil-streamlit.mi2.ai
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: streamlit-fersoil
              port:
                number: 80