apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-deployment
  labels:
    app: streamlit
    www: "true"
  namespace: user-fersoil
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit
          image: tkwiecinski/streamlit_translator:v0.0.3
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
          livenessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
              scheme: HTTP
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
              scheme: HTTP
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 745Mi
      automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-fersoil
  namespace: user-fersoil
spec:
  type: ClusterIP
  selector:
    app: streamlit
  ports:
    - name: streamlit-port
      protocol: TCP
      port: 8501
      targetPort: 4180
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: streamlit-app
  namespace: user-fersoil
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: user-fersoil-streamlit.mi2.ai
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: streamlit-fersoil
              port:
                number: 4180